kms = float(input('Digite o numero de km percoridos com o carro: '))
dias = int(input('Digite o numero de dias: '))
valor_km = float(kms * 0.15)
valor_dias = float(dias * 60)
valor_total = float(valor_km + valor_dias)
print('O valor do aluguel por dia do carro é R$60')
print('Com um acressimo de 0,15 centavos por km rodado')
print(f'Ja que voce percoreu {kms}km o valor estra por km rodado será: {valor_km}')
print(f'ja que voce ficou com o carro por {dias} dias o valor a pagar pelos dias que voce ficou com o carro é R${valor_dias}')
print(f'O valor total a ser pago é R${valor_total}')