n1 = float(input('Digite o primeiro numero'))
n2 = float(input('Digite o segundo numero'))
print(f'Soma dos numero: {n1 + n2}')
print(f'subtração dos numeros {n1 - n2}')
print(f'multiplicação dos numeros{n1 * n2}')
print(f'Divisão dos numeros: {n1 / n2}')
print(f'Valor do resto da divisão:{n1 % n2}')
print(f'Valor ultilizado na divisão{n1 // n2}')
print(f'Potencia{n1 ** n2}')
