numero = int(input('escolha uma tabuada'))
result1 = numero * 1
result2 = numero * 2
result3 = numero * 3
result4 = numero * 4
result5 = numero * 5
result6 = numero * 6
result7 = numero * 7
result8 = numero * 8
result9 = numero * 9
result10 = numero * 10
print(f'{numero}x1={result1}')
print(f'{numero}x2={result2}')
print(f'{numero}x3={result3}')
print(f'{numero}x4={result4}')
print(f'{numero}x5={result5}')
print(f'{numero}x6={result6}')
print(f'{numero}x7={result7}')
print(f'{numero}x8={result8}')
print(f'{numero}x9={result9}')
print(f'{numero}x10={result10}')